export const metadata={title:"Privacy Policy",description:"TrafficCampaign privacy policy and current data-processing practices.",alternates:{canonical:"/privacy"}};
export default function Page(){return <div className="article"><div className="kicker">Privacy</div><h1>Privacy Policy</h1><p className="lead">TrafficCampaign is designed to collect as little visitor data as practical.</p>
<h2>Current site behavior</h2><p>The core website does not require an account and does not require personal information to use its guides, calculators, templates, or Campaign Academy.</p>
<h2>Essential storage</h2><p>TrafficCampaign may use first-party browser storage to remember your privacy preference and support basic site functionality. This is not used to build an advertising profile.</p>
<h2>Analytics</h2><p>Optional analytics are disabled by default. TrafficCampaign does not currently load Google Analytics, Google Tag Manager, Meta Pixel, session replay, heatmap, or advertising-tracking scripts on page load.</p><p>If analytics are added later, the site is designed so optional analytics should load only after a visitor affirmatively chooses to allow analytics through the privacy controls.</p>
<h2>Calculator and builder inputs</h2><p>Current calculator, UTM Builder, and Campaign Builder inputs are processed in your browser to produce the requested result. These tools do not require an account.</p>
<h2>UTM and URL safety</h2><p>Do not place names, email addresses, customer IDs, health information, or other sensitive or personally identifiable information in campaign URLs or UTM parameters.</p>
<h2>Third-party services</h2><p>If TrafficCampaign later adds analytics, newsletters, advertising, forms, embedded media, or other third-party services, this policy will be updated to describe those services and relevant choices.</p>
<h2>Your privacy choice</h2><p>You can reopen Privacy Settings from the site footer and change your analytics preference at any time.</p>
<h2>Contact</h2><p>Questions about this policy can be sent to <a href="mailto:hello@trafficcampaign.com">hello@trafficcampaign.com</a>.</p>
<p><strong>Last updated:</strong> August 8, 2026.</p></div>}